version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "vite"
      - dependency-name: "@vitejs/plugin-react"
      - dependency-name: "esbuild"
