/**
 * Gemini Service
 *
 * Provides an interface for interacting with the Google Gemini AI models
 * through a secure backend proxy to protect API keys.
 */

/**
 * Interface representing a message in the chat history.
 */
interface ChatHistoryMessage {
  role: 'user' | 'model';
  parts?: any[];
  text?: string;
  image?: string;
}

/**
 * Sends a chat request to the Gemini AI model.
 *
 * @param messages - An array of chat messages representing the conversation history.
 * @param apiKey - Optional custom API key. If not provided, the backend default will be used.
 * @param systemInstruction - Optional system prompt to define the AI's persona and rules.
 * @returns The text response generated by the AI model.
 * @throws {Error} If the backend request fails or the API returns an error.
 */
export async function generateChatResponse(
  messages: ChatHistoryMessage[],
  apiKey?: string,
  systemInstruction?: string
) {
  try {
    const lastMessage = messages[messages.length - 1];
    const history = messages.slice(0, -1).map(m => ({
      role: m.role,
      text: m.text || m.parts?.[0]?.text,
      image: m.image || null
    }));

    const response = await fetch('/api/chat', {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        message: lastMessage.text || lastMessage.parts?.[0]?.text,
        image: lastMessage.image || null,
        history,
        systemInstruction: systemInstruction || "You are Forge Assistant, a specialized AI for DIY engineering, automotive repair, and hardware development.",
        customApiKey: apiKey
      }),
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      throw new Error(errData.error || "Failed to generate chat response.");
    }

    const data = await response.json();
    return data.text;
  } catch (error) {
    console.error("Gemini Backend Error:", error);
    throw error;
  }
}

/**
 * Analyzes an image using Gemini AI's multimodal capabilities.
 *
 * @param prompt - The instruction or question about the image.
 * @param base64Image - The image data encoded as a base64 string.
 * @param apiKey - Optional custom API key.
 * @param systemInstruction - Optional system prompt for the visual analysis persona.
 * @returns The textual analysis of the image.
 * @throws {Error} If the backend request fails.
 */
export async function analyzeImage(
  prompt: string,
  base64Image: string,
  apiKey?: string,
  systemInstruction?: string
) {
  try {
    const response = await fetch('/api/chat', {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        message: prompt,
        image: `data:image/jpeg;base64,${base64Image}`,
        history: [],
        systemInstruction: systemInstruction || "You are an expert visual inspector.",
        customApiKey: apiKey
      }),
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      throw new Error(errData.error || "Failed to analyze image.");
    }

    const data = await response.json();
    return data.text;
  } catch (error) {
    console.error("Gemini Backend Error:", error);
    throw error;
  }
}
